#%RAML 1.0
title: account-demo
/accounts:
  post:
    description: Create account for customer
    body:
      application/json:
        example: !include examples/account.json
    responses:
      201:
        body:
          application/json:
            example: !include /examples/accountResponse.json
          
  get:
    description: Fetch account on basic of CustomerId
    queryParameters:
      customerId:
        type: string
        required: true
        example: "cust12345"
    responses:
      200:
        body:
          application/json:
            example: !include examples/account.json